{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tc",
    "module": "tcmap",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tcmap-1.0.0.aar",
          "url": "tcmap-1.0.0.aar",
          "size": 173023,
          "sha512": "8b916f58e502eb1417c5d21767858cfc951f1e9001b6c4dc2450b1fe8bdfd8a033affddb299ec6cf6ba5c4c76dd1e16b42852546eb59d58e4147e8582247472a",
          "sha256": "afa019a0ded6ae8de9dc3be1c24114ca929f274239f8cc6e5272dba6969bb18c",
          "sha1": "ba67e3fd262e873a68d741c833e4a8d26d72705a",
          "md5": "88b93286a183d20a9609f22f9809f801"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-compose",
          "version": {
            "requires": "6.12.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tcmap-1.0.0.aar",
          "url": "tcmap-1.0.0.aar",
          "size": 173023,
          "sha512": "8b916f58e502eb1417c5d21767858cfc951f1e9001b6c4dc2450b1fe8bdfd8a033affddb299ec6cf6ba5c4c76dd1e16b42852546eb59d58e4147e8582247472a",
          "sha256": "afa019a0ded6ae8de9dc3be1c24114ca929f274239f8cc6e5272dba6969bb18c",
          "sha1": "ba67e3fd262e873a68d741c833e4a8d26d72705a",
          "md5": "88b93286a183d20a9609f22f9809f801"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "tcmap-1.0.0-sources.jar",
          "url": "tcmap-1.0.0-sources.jar",
          "size": 20850,
          "sha512": "aeb47f6488675b340515df46a28ddcdaaa9e776a8cd9b4f3a56e0d8ecc396a44c33269bebdc0d81ada4f02993317b71807fc1066ebd1a6f8c1e6c3c73b0e65dc",
          "sha256": "dbd4ab29681a9ce9d67d629cf09e4a2ee445fd8c32bdf19a299c162f8741aabe",
          "sha1": "4671c406a610296662a9a57ad29dc49b7cecef96",
          "md5": "83cb7bf5e7a0e7a7687df23ea6dd747b"
        }
      ]
    }
  ]
}
